apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: acs-process-scan-results
spec:
  params: 
  - name: include-rox-output
    type: string
  - name: perl-script-location
    type: string
  results:
    - name: scan-result
  steps:
  - name: show-rox-output
    image: quay.io/marrober/ubi8-perl:1
    resources: {} 
    workingDir: /files
    script: >-
      #!/usr/bin/env bash

      if [[ "$(params.include-rox-output)" == "true" ]]; then

        ls *.scan-result

        fileList=`ls *.scan-result`

        for file in $fileList   

        do

          originalFilename=`echo $file | sed 's/.scan-result//g'`

          echo "---------------------------------------------------"

          echo $originalFilename

          echo "- - - - - - - - - - - - - - - - - - - - - - - - - -"

          cat "$file"

        done

      fi

  - name: scan-results
    image: quay.io/marrober/ubi8-perl:1
    resources: {}
    workingDir: /files
    script: >-
      #!/usr/bin/env bash

      perl $(params.perl-script-location)/acs-process-scan-results.pl

      if [[ "$?" == "0" ]]
      
      then

        echo "Setting overall result to pass"

        echo -n "pass" | tee $(results.scan-result.path) >> /dev/null

      else 

        echo "Setting overall result to fail"

        echo -n "fail" | tee $(results.scan-result.path) >> /dev/null

      fi

  workspaces:
  - name: files
    mountPath: /files
